detectors:
  UtilityFunction:
    exclude:
      - 'options'
      - 'save_user'
      - 'read_user'
      - 'get_user'

  IrresponsibleModule:
    exclude:
      - 'Home'
      - 'LoginPage'
      - 'RegistrationPage'
      - 'MenuSection'
      - 'MyPage'
      - 'User'

  TooManyInstanceVariables:
    max_instance_variables: 10

  TooManyStatements:
    max_statements: 15

  DuplicateMethodCall:
    exclude:
      - 'UserHelper#register_user'
