Layout/TrailingWhitespace:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Enabled: 50

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false
  